server:
  port: 8088


spring:
  output:
     ansi:
         enabled: always

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  messages:
    basename : messages


logging:
  level:
    org.springframework: info



