spring:
  output:
     ansi:
         enabled: always

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG



